### ISSUE TITLE
安卓手机无法安装证书

### ISSUE THREAD

**Issue by Perterually** [alibaba/lightproxy#111]
**Describe the bug**

**To Reproduce**
1. 无法安装证书

**Expected behavior**
无

**Screenshots**
![webwxgetmsgimg](https://user-images.githubusercontent.com/12246868/80331022-7dba4080-8879-11ea-8692-5405d5b3da35.jpg)

**Desktop (please complete the following information):**
 - OS: Android 10; ONEPLUS

**Log**
无

**Comment by xcodebuild** [comment]
请参考 https://support.google.com/pixelphone/answer/2844832?hl=zh-Hans&visit_id=637235552913113911-3967826924&rd=1

给 Android 设备安装证书 

> - 打开手机的“设置”应用。
> - 依次点按安全性和位置信息 然后 高级 然后 加密与凭据。
> - 在“凭据存储”下方，点按从存储设备安装。
> - 点按左上角的“菜单”图标 菜单。
> - 在“打开文件”下方，点按证书所在的位置。
> - 点按相应文件。（如果需要，请输入密钥库密码）。点按确定。
> - 为证书输入名称。
> - 选择 VPN 和应用或 WLAN。
> - 点按确定。

需要注意的是，高版本 Android 默认三方应用是不使用用户证书的，安装完证书后你可以先用 Chrome 试一下。

**Comment by Perterually** [comment]
可以了，谢谢．
