### ISSUE TITLE
cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by aladdin-add** [alibaba/lightproxy#115]
**To Reproduce**
1. 下载最新版本(1.1.13)
2. 点击安装 => 下一步
3. 截图内容:
![image](https://user-images.githubusercontent.com/13050025/80674736-51a2f780-8ae5-11ea-92a2-791fb9861384.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos 10.15.4 (19E266)

**Log**
Log at `~/Library/Logs/Electron/renderer.log` and `~/Library/Logs/Electron/main.log`

**Comment by xcodebuild** [comment]
参考 https://support.apple.com/en-us/HT202491

打开设置 => 安全

![image](https://user-images.githubusercontent.com/5436704/80677372-5a96c780-8aeb-11ea-853b-d327dd9f34b2.png)

点击 Open anyway，然后确定

可能需要补充到 README

**Comment by xcodebuild** [comment]
已经补充文档到：https://lightproxy.org/zh-CN/doc/faq#cannot-be-opened-because-the-developer-cannot-be-verified
