### ISSUE TITLE
node.js 发出的请求，抓不到包，能不能加个插件或者集成一个开关。

### ISSUE THREAD

**Issue by Faithree** [alibaba/lightproxy#116]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xcodebuild** [comment]
可以参考类似于

![image](https://user-images.githubusercontent.com/5436704/80677513-9af64580-8aeb-11ea-9aed-0c239d5aca3e.png)

把这个功能做进 menubar 中，然后根据当前的 `proxy port/socks port` 自动把指令复制到剪贴板

```
export https_proxy=http://127.0.0.1:HTTP代理端口 http_proxy=http://127.0.0.1:HTTP代理端口 all_proxy=socks5://127.0.0.1:SOCKS代理端口
```

## 相关信息

- 和 menubar 相关的代码：https://github.com/alibaba/lightproxy/blob/develop/src/renderer/extensions/rule-editor/index.tsx#L32

- 获取 port 的方式 https://github.com/alibaba/lightproxy/blob/develop/src/renderer/utils.ts#L22

- socks port 的方式可以先简单的使用 `Number.parseInt(http port, 10) + 1`

**Comment by xcodebuild** [comment]
已经由 #165 实现了
