### ISSUE TITLE
response乱码

### ISSUE THREAD

**Issue by time-Is-Money** [alibaba/lightproxy#131]
请求返回的数据在Lightproxy里展示的是乱码，这样在使用中非常不方便

**Comment by xcodebuild** [comment]
乱码的是二进制文件么，如果二进制文件乱码是符合预期的，我这边其他的 response 没有问题

![image](https://user-images.githubusercontent.com/5436704/81769956-6fbf1d80-9511-11ea-8bd9-0c053f86d058.png)
