### ISSUE TITLE
怎么只显示指定地址的抓包情况

### ISSUE THREAD

**Issue by Phil-Xue** [alibaba/lightproxy#134]
比如只看www.baidu.com

**Comment by xcodebuild** [comment]
两种方案

## 搜索
一个是抓包界面可以直接在左下角搜索过滤要抓包的内容

![image](https://user-images.githubusercontent.com/5436704/82064901-f5082500-96ff-11ea-98e5-f32fe9fe4810.png)
## enable/disable
`enable://hide` 表示在抓包界面不显示，`disable://hide` 则是让 `enable://hide` 失效

可以先隐藏所有的请求，然后单独显示和 `baidu.com` 相关的。

```js
/.*/ enable://hide
*.baidu.com disable://hide
baidu.com disable://hide
```
