### ISSUE TITLE
iOS 你的连接不是私密连接

### ISSUE THREAD

**Issue by jiarukai** [alibaba/lightproxy#138]
已经按照描述文件并信任；

iOS 你的连接不是私密连接

**Comment by xcodebuild** [comment]
> 到 `设置 => 通用 => 关于本机 => （拉到最下面）证书信任设置，勾上 LightProxy 的证书

参考 https://lightproxy.org/zh-CN/doc/wireless#ios-%E7%94%A8%E6%88%B7 确认一下，另外不同机器生成的证书是不同的，需要单独安装
