### ISSUE TITLE
资源 pending 问题

### ISSUE THREAD

**Issue by limerickgds** [alibaba/lightproxy#142]
我遇到应该三个问题：
1. lightproxy dns 缓存会有失败情况，需要重启，更新。
2. 页面加载内容多，如果有比较大 xhr 请求的 response body ，资源会 pending。 
3. url 超级长会 pending（这个不清楚跟 lightproxy 有关部）

**Comment by xcodebuild** [comment]
试了一下超长 url，并没有产生什么额外的影响。

不过似乎问题的本质是当真正的 server 的响应较慢时（TTFB 长），经过 lightproxy 代理的情况下在 Chrome 中反应为长时间的 `pending`

**Comment by xcodebuild** [comment]
相关为什么 Chrome 会出现长时间 pending 的分析文章：https://fex.baidu.com/blog/2015/01/chrome-stalled-problem-resolving-process/

> 在请求能够被发出去前的等等时间。包含了用于处理代理的时间。另外，如果有已经建立好的连接，那么这个时间还包括等待已建立连接被复用的时间，这个遵循Chrome对同一源最大6个TCP连接的规则。

使用 http://slowwly.robertomurray.co.uk/delay/3000/url/http://www.baidu.com 测试确实如此，反应为 3s 以上的 pending，但是最后加载完成后正确显示为 TTFB。

![image](https://user-images.githubusercontent.com/5436704/83016461-8e1a3280-a054-11ea-9407-2d5589e5a3d0.png)

**Comment by xcodebuild** [comment]
经过测试后发现和代理无关，似乎是 devtools 本身的行为，相关的 Chrome 反馈，TTFB 很慢的请求会一直 pending，返回回来的 timeline 又是正确的

https://support.google.com/chrome/thread/49442697?hl=en

**Comment by limerickgds** [comment]
@xcodebuild 但是关闭 lightproxy 就ok了，难道是叠加的因素

**Comment by xcodebuild** [comment]
推测是代理请求太多影响了性能，考虑通过实现白名单模式提高性能：https://github.com/alibaba/lightproxy/issues/150
