### ISSUE TITLE
iCloud not work with proxy

### ISSUE THREAD

**Issue by Pain-and-Love** [alibaba/lightproxy#149]
能支持自定义白名单嘛？
icloud同步功能用不了。。

**Comment by xcodebuild** [comment]
漏了 iCloud 相关域名，已经在 https://github.com/alibaba/lightproxy/commit/2ca56413baabbdbcf928d2db05e57e0414319e09 中修复

也可以临时通过添加

```
disable://intercept ***.apple-cloudkit.com ***.icloud.com ***.icloud-content.com
```

来修复 iCloud 同步问题。

## 关于白名单

目前对于规则比较熟悉的用户可以通过

```
/.*/  disable://intercept
```

默认取消对所有域名的 HTTPS 代理，然后只针对开启的规则 `enable://intercept`

白名单代理功能会在后面的版本做，主要要考虑如何降低用户理解成本，防止部分用户因为白名单设置导致代理不生效的问题难以排查。

Feature Request 合并到 https://github.com/alibaba/lightproxy/issues/150

**Comment by Pain-and-Love** [comment]
> 漏了 iCloud 相关域名，已经在 [2ca5641](https://github.com/alibaba/lightproxy/commit/2ca56413baabbdbcf928d2db05e57e0414319e09) 中修复
> 
> 也可以临时通过添加
> 
> ```
> disable://intercept ***.apple-cloudkit.com ***.icloud.com ***.icloud-content.com
> ```
> 
> 来修复 iCloud 同步问题。
> 
> ## 关于白名单
> 目前对于规则比较熟悉的用户可以通过
> 
> ```
> /.*/  disable://intercept
> ```
> 
> 默认取消对所有域名的 HTTPS 代理，然后只针对开启的规则 `enable://intercept`
> 
> 白名单代理功能会在后面的版本做，主要要考虑如何降低用户理解成本，防止部分用户因为白名单设置导致代理不生效的问题难以排查。
> 
> Feature Request 合并到 #150

***.icloud.com.cn 哈

**Comment by xcodebuild** [comment]
Release `1.1.22` 已经修复，close
