### ISSUE TITLE
【功能】切换系统代理快捷键提供关闭功能。

### ISSUE THREAD

**Issue by kisnows** [alibaba/lightproxy#183]
![image](https://user-images.githubusercontent.com/9394000/86731172-d9672e00-c061-11ea-937b-ab74bddea391.png)
从某个版本更新以后，为了方便使用软件提供了通过键盘快捷键来切换系统代理的功能，而且默认开启无法关闭。
考虑到全局快捷键经常会和其他软件冲突，希望提供一个可以关闭键盘快捷键的选项。

**Comment by LeezQ** [comment]
+1 ，这种快捷键至少可以有个关闭功能吧，搞得全局的快捷键跟别的 app 冲突，找了半天。

**Comment by xcodebuild** [comment]
当前升级到最新版是用的 (Cmd+Shift+L）至少可以表面和 vscode 等常用软件冲突。

关闭功能会尽快提供

**Comment by ron0115** [comment]
请尽快解决。vscode直接冲突。

**Comment by xcodebuild** [comment]
@ron0115 如果是 `Cmd+Shift+P` 冲突，升级到最新版已经换成了 `Cmd+Shift+L`

**Comment by ron0115** [comment]
> @ron0115 如果是 `Cmd+Shift+P` 冲突，升级到最新版已经换成了 `Cmd+Shift+L`

好的 已经更新，谢谢

**Comment by caijinyc** [comment]
+10086 ，这种快捷键至少可以有个关闭功能吧，搞得全局的快捷键跟别的 app 冲突，找了半天。

**Comment by AmosJin** [comment]
> @ron0115 如果是 `Cmd+Shift+P` 冲突，升级到最新版已经换成了 `Cmd+Shift+L`

`Cmd+Shift+L` 还是和 VS Code 的全部模式选择冲突了

**Comment by xcodebuild** [comment]
在 beta 版本中支持了该功能：

- 快捷键由 Cmd+Shift+L 改为 Cmd+Shift+Alt+L
- 设置界面提供全局快捷键的开关，可以关闭

可以下载 `1.1.27-beta-3` 以后的版本使用：https://github.com/alibaba/lightproxy/releases
