### ISSUE TITLE
window客户端使用 fileScript 规则会自动添加 resCors 规则导致报错

### ISSUE THREAD

**Issue by ycr6708536** [alibaba/lightproxy#185]
使用fileScript 会自动添加 Cros 请求头报错

**.test.a.com/a/b scriptfile://C:\Users\ice\Documents\项目文档\07\proxy\unbind.js resCors://*
**.test.a.com/a/b scriptfile://C:\Users\ice\AppData\Local\Temp\lightproxy\1-507.txt

错误信息如下
From: whistle@2.5.11
Node: v12.13.0
Date: 2020/7/8 上午9:57:05
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["__lightproxy-rules__"]
    at storeHeader (_http_outgoing.js:432:5)
    at processHeader (_http_outgoing.js:427:3)
    at ServerResponse._storeHeader (_http_outgoing.js:332:11)
    at ServerResponse.writeHead (_http_server.js:303:8)
    at C:\Users\ice\AppData\Roaming\LightProxy\files\node\node_modules\whistle\lib\inspectors\res.js:909:25
    at C:\Users\ice\AppData\Roaming\LightProxy\files\node\node_modules\q\q.js:1249:26
    at _fulfilled (C:\Users\ice\AppData\Roaming\LightProxy\files\node\node_modules\q\q.js:854:54)
    at C:\Users\ice\AppData\Roaming\LightProxy\files\node\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\ice\AppData\Roaming\LightProxy\files\node\node_modules\q\q.js:816:13)
    at C:\Users\ice\AppData\Roaming\LightProxy\files\node\node_modules\q\q.js:570:49

**Comment by xcodebuild** [comment]
自动添加 cors 头是默认行为，否则大部分用户都会忘记，不是导致这个错误的原因

这个错误的原因是因为路径有中文，中文被塞进 header 里导致的，这个问题在 https://github.com/alibaba/lightproxy/releases/tag/v1.1.27-beta-1 被修复了

**Comment by gongeek** [comment]
> 自动添加 cors 头是默认行为，否则大部分用户都会忘记，不是导致这个错误的原因
> 
> 这个错误的原因是因为路径有中文，中文被塞进 header 里导致的，这个问题在 https://github.com/alibaba/lightproxy/releases/tag/v1.1.27-beta-1 被修复了

这个默认设置能搞个全局设置选项吗？我是直接点的左侧 rules按钮添加 nodejs自定义规则 发现代码无论怎么设置 ctx.set('access-control-allow-origin','https://xx.com') 都无效 都会是access-control-allow-origin: * 导致那种强校验跨域设置的站点浏览器会报跨域错误。 最后排查半天发现 default rules whiste 背后加了个 resCors://

建议这个默认行为可以搞个关闭的全局设置选项
