### ISSUE TITLE
win10安装失败

### ISSUE THREAD

**Issue by zhengb1019** [alibaba/lightproxy#192]
win10安装之后，双击桌面的快捷图标打开软件之后会弹出一个错误窗口（图3），并且被图一遮挡不能点击到，然后就一直停留这个状态打不开了。

![1](https://user-images.githubusercontent.com/19563688/87742978-7e2ffb00-c81a-11ea-9a38-6a1d0fdbd400.png)
![2](https://user-images.githubusercontent.com/19563688/87743015-8ee07100-c81a-11ea-927e-1d50bd0725e1.png)
![3](https://user-images.githubusercontent.com/19563688/87743021-9142cb00-c81a-11ea-9dc7-b2070e2ad4f8.jpg)

**Comment by xcodebuild** [comment]
请重新下载最新版（`1.1.31`) 解决
