### ISSUE TITLE
这个项目为什么没用到anyproxy呢?

### ISSUE THREAD

**Issue by jjeejj** [alibaba/lightproxy#20]
anyporxy 嵌入服务端代码中使用
lightproxy 桌面端， 齐活了

**Comment by xcodebuild** [comment]
没有用到 `anyproxy`，底层是基于 [whistle](https://github.com/avwo/whistle) 的

因为相对来说 `whistle` 底层提供的已有规则和各种插件更加便捷一些，`anyproxy` 更适合作为一个三方库来使用（如你所说嵌入服务端代码使用），而 `whistle` 的规则则适合开发者直接书写快速使用。

**Comment by lizy0329** [comment]
anyproxy 功能太弱了
