### ISSUE TITLE
代理未启动

### ISSUE THREAD

**Issue by assmdx** [alibaba/lightproxy#204]
![image](https://user-images.githubusercontent.com/19722693/93575579-6b79a400-f9cc-11ea-8ea4-25af4b267b04.png)
![image](https://user-images.githubusercontent.com/19722693/93575594-703e5800-f9cc-11ea-8936-0c9ca3df0ea5.png)

**Comment by xcodebuild** [comment]
尝试

```js
rm -rf '~/Library/Application Support/LightProxy/files'
```

后重启应用

**Comment by assmdx** [comment]
谢谢你~
