### ISSUE TITLE
mac下不停地发通知

### ISSUE THREAD

**Issue by assmdx** [alibaba/lightproxy#207]
![image](https://user-images.githubusercontent.com/19722693/93709220-1a55e580-fb6f-11ea-92a7-1dd8f7fe4596.png)

**Comment by xcodebuild** [comment]
发这个通知是因为代理重启了，代理在不停的自己重启么

**Comment by xcodebuild** [comment]
可能是近期版本的断网检测异常导致的，可以尝试 https://github.com/alibaba/lightproxy/releases/tag/v1.1.39-beta-5 是否解决了该问题

**Comment by xcodebuild** [comment]
fixed with https://github.com/alibaba/lightproxy/releases/tag/v1.1.39
