### ISSUE TITLE
redirect规则不生效

### ISSUE THREAD

**Issue by vonlyinno** [alibaba/lightproxy#208]
版本：1.1.38

设置重定向 规则不生效，无法正常响应：
`www.ifeng.com redirect://http://www.aliexpress.com/`

![image](https://user-images.githubusercontent.com/9960612/93844042-80a54a00-fcce-11ea-9264-f2ab34a1dbab.png)

**Comment by xcodebuild** [comment]
抱歉响应慢了些，已经在 https://github.com/alibaba/lightproxy/releases/tag/v1.1.40-beta-3 修复，可以下载 beta 版

没有问题的话会在后面的 release 中正式修复

**Comment by xcodebuild** [comment]
fixed in https://github.com/alibaba/lightproxy/releases/tag/v1.1.40

**Comment by lizy0329** [comment]
版本：v1.1.41

www.ifeng.com redirect://`http://www.aliexpress.com/${query}` 也无法生效

···url
http://www.aliexpress.com/#/link
···
www.ifeng.com redirect://{url}

也是如此
