### ISSUE TITLE
抓取html请求，看不到html代码

### ISSUE THREAD

**Issue by assmdx** [alibaba/lightproxy#211]

**Comment by assmdx** [comment]
返回内容为html， 软件上不显示

**Comment by xcodebuild** [comment]
![image](https://user-images.githubusercontent.com/5436704/95563857-89c54380-0a50-11eb-9884-3c877c528140.png)
又可以复现的步骤和线上链接么

**Comment by assmdx** [comment]
目前没有，我再看下。
