### ISSUE TITLE
lightproxy=true这个调试功能貌似对浏览器访问手机本地路径的文件不起作用

### ISSUE THREAD

**Issue by ZhangKejun** [alibaba/lightproxy#212]
对类似：http://xxx  的可以调试

对类似：file://xxx 的不可以调试

**Comment by xcodebuild** [comment]
`file://` 应该不会走代理，有什么特殊的原因一定要访问 `file://` 么，可以考虑用规则 mock 一个页面么

**Comment by ZhangKejun** [comment]
> `file://` 应该不会走代理，有什么特殊的原因一定要访问 `file://` 么，可以考虑用规则 mock 一个页面么

我想要实现类似微信小程序开发工具里面的远程真机调试功能，类型safari浏览器、谷歌浏览器的调试功能；

**Comment by xcodebuild** [comment]
remote debug 功能确实就是类似的功能，但是对 `file://` 协议代理是无法生效的

**Comment by Faithree** [comment]
@xcodebuild 请教一下，移动端调试，真机的 url 带上 lightproxy=true 不也是会很麻烦吗，有没有办法不需要修改 真机  url,直接开启真机调试

**Comment by xcodebuild** [comment]
可以在规则里写明
```
匹配规则 whistle.chii-internal://debug
```

之所以采用目前的设计是因为如果所有的页面都注入 debug 脚本会有些问题：

- 有些页面不兼容
- 性能会很差

**Comment by Faithree** [comment]
@xcodebuild 这个方法可以，尽量避免所有页面一起使用调试模式
再请教个问题，我看这个 LightProxy 默认 12888 端口，浏览器访问，会弹出 auth 校验，想问下默认密码是什么，可以自己修改吗
![image](https://user-images.githubusercontent.com/21101396/95810992-e07a9800-0d44-11eb-9890-6354e5b8e7c1.png)

**Comment by xcodebuild** [comment]
![image](https://user-images.githubusercontent.com/5436704/95811116-29325100-0d45-11eb-8307-f534f1ab5a4d.png)

密码是启动时随机生成的，为了安全性考虑。

可以在 lightproxy hover 到右下角，点查看 whistle 密码
