### ISSUE TITLE
windows 版无法引入全局安装的 whistle 插件

### ISSUE THREAD

**Issue by flyfly6** [alibaba/lightproxy#213]
windows 版无法引入全局安装的 whistle 插件
这里的 \n 被转义成换行符了
https://github.com/alibaba/lightproxy/blob/13e2ca98553b591d0c7278f99c4adf1e96ee4798/vendor/whistle-start/index.js#L25-L28
修改了下就可以正常引入了
```javascript
 ).concat( 
     glob.sync(`${process.env.AppData}\\npm\\node_modules`) 
 ).concat( 
     glob.sync(`${process.env.AppData}\\npm\\node_modules`) 
```

**Comment by xcodebuild** [comment]
thx, 考虑来个 pull request 么 👍

**Comment by xcodebuild** [comment]
fixed in https://github.com/alibaba/lightproxy/releases/tag/v1.1.40
