### ISSUE TITLE
window 如何彻底删除，删掉软件，重新装，还是原来的配置文件

### ISSUE THREAD

**Issue by Faithree** [alibaba/lightproxy#214]
window 如何彻底删除，删掉软件，重新装，还是原来的配置文件

**Comment by xcodebuild** [comment]
删除 `C:\Users\用户名\AppData\Roaming\LightProxy` 即可

**Comment by Faithree** [comment]
> 删除 `C:\Users\用户名\AppData\Roaming\LightProxy` 即可

删了还行不行，我重新装这个软件，还要会有原来的规则表在上面，我把规则表都注释了之后，发现还是抓不到包，浏览器提示
![image](https://user-images.githubusercontent.com/21101396/95703236-3ede4280-0c81-11eb-891b-c9ad4f142bcd.png)
麻烦看看是什么问题？

**Comment by Faithree** [comment]
![image](https://user-images.githubusercontent.com/21101396/95703321-6a612d00-0c81-11eb-850c-65949fad4e0b.png)

**Comment by xcodebuild** [comment]
参考 https://lightproxy.org/zh-CN/doc/faq#证书错误 的 windows 部分，用管理员权限 help-install cert

**Comment by Faithree** [comment]
> 参考 [https://lightproxy.org/zh-CN/doc/faq#证书错误](https://lightproxy.org/zh-CN/doc/faq#%E8%AF%81%E4%B9%A6%E9%94%99%E8%AF%AF) 的 windows 部分，用管理员权限 help-install cert

可以了，谢谢
