### ISSUE TITLE
win7 安装提示  未安装证书/代理helper或者已经过期，需要安装，可能会需要输入登录用户的密码

### ISSUE THREAD

**Issue by luckdog2018** [alibaba/lightproxy#216]
安装提示：

The certificate and proxy helper is not installed or has expired. You need to install. You may need to enter the password of the login user.

未安装证书/代理helper或者已经过期，需要安装，可能会需要输入登录用户的密码。

**Comment by xcodebuild** [comment]
属于正常行为，点击确认后会安装证书并且重启，记得在属性 =》 兼容性 开启管理员权限

**Comment by luckdog2018** [comment]
多谢
