### ISSUE TITLE
Proxy breaks Chrome

### ISSUE THREAD

**Issue by bc-185** [alibaba/lightproxy#217]
When I try to access a website and LightProxy is enabled, I get an `NET::ERR_CERT_AUTHORITY_INVALID` error that cannot be bypassed until I close LightProxy.

**Comment by xcodebuild** [comment]
Follow document here: https://lightproxy.org/doc/faq#certificate-error

Windows user not `admin` to install cert

**Comment by bc-185** [comment]
Thank you for helping me get it working!
