### ISSUE TITLE
LightProxy启用GPU加速 ，导致屏幕花屏；重启可恢复；

### ISSUE THREAD

**Issue by nelhu** [alibaba/lightproxy#219]
### System
MacOS Catalina 10.15.7

### LightProxy Version
1.1.34

### Recover Step
随机出现

![image](https://user-images.githubusercontent.com/24311105/98939890-1b7b1180-2525-11eb-9b37-74cd5ef7e9f0.png)

**Comment by xcodebuild** [comment]
fixed in https://github.com/alibaba/lightproxy/releases/tag/v1.1.40
