### ISSUE TITLE
windows 下的关闭按钮在哪里

### ISSUE THREAD

**Issue by maicWorkGithub** [alibaba/lightproxy#22]
![image](https://user-images.githubusercontent.com/15863224/71808954-fec2b180-30a9-11ea-9e68-61e1a97b83cc.png)

另外，左上角的那三个点是干吗用的 😹

**Comment by xcodebuild** [comment]
看了下应该是个 bug，应该考虑在 Windows 下隐藏三个点（本来是 macOS 的操作栏）显示 Windows 原有的 titlebar

**Comment by xcodebuild** [comment]
作为临时的解决方案可以先去 任务栏 hover 上去的 `X` 来关闭，下个版本会修复这个问题

**Comment by xcodebuild** [comment]
`1.1.1-beta-1` 已经修复
