### ISSUE TITLE
remote debugger 损坏

### ISSUE THREAD

**Issue by xcodebuild** [alibaba/lightproxy#221]
![image](https://user-images.githubusercontent.com/5436704/99336576-5df17500-28bc-11eb-9c44-31ab3a7c9887.png)

- inspect 看不到页面
- darkmode 下这个页面的样式有点奇怪

**Comment by musistudio** [comment]
remote debugger损坏是因为原chii插件不兼容最新版ws库导致，[在ws最新版中url被设定成了只读属性](https://github.com/websockets/ws/commit/eabed8fcc3694893e603460008994e3f4bcbaf42)，[但是chii插件有修改url的操作](https://github.com/liriliri/chii/blob/master/server/lib/WebSocketServer.js)。

这个如果提PR的话应该提到插件那边比较好吧。

**Comment by xcodebuild** [comment]
是的，lightproxy 可以从原插件的仓库更新依赖



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: musi <notifications@github.com&gt;
发送时间: 2020年11月29日 00:39
收件人: alibaba/lightproxy <lightproxy@noreply.github.com&gt;
抄送: xcodebuild <me@xcodebuild.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/lightproxy] remote debugger 损坏 (#221)

**Comment by musistudio** [comment]
刚去原插件库看了一下，已经有人提了PR了，现在等作者合并应该就没问题了

**Comment by xcodebuild** [comment]
在 https://github.com/alibaba/lightproxy/releases/tag/v1.1.41-beta-10 中修复了
