### ISSUE TITLE
手机代理后，没有网络

### ISSUE THREAD

**Issue by Seifon** [alibaba/lightproxy#222]
电脑mac系统，手机iOS系统

手机wifi填了代理ip和端口，可是没有网络

**Comment by xcodebuild** [comment]
确认下以下信息：
- 是否用 Safari 或者 Chrome 测试
- 手机和电脑是否在一个wifi
- 手机有没有挂 vpn
- 手机扫描证书二维码是否能访问

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Seifon "<notifications@github.com&gt;;
发送时间：2020年12月6日(星期天) 晚上6:23
收件人："alibaba/lightproxy" <lightproxy@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[alibaba/lightproxy] 手机代理后，没有网络 (#222)
-----------------------------------

 

 
电脑mac系统，手机iOS系统
 
手机wifi填了代理ip和端口，可是没有网络
