### ISSUE TITLE
[手机代理]页面，下载证书是个二维码，对无法扫码的场景不友好[狗头]

### ISSUE THREAD

**Issue by KevinChen073** [alibaba/lightproxy#227]
[手机代理]页面，下载证书是个二维码，对无法扫码的场景不友好。（例如模拟器，云真机等），能否在二维码下面也增加URL的展示，并且点击一键粘贴到剪贴板，方便操作。

**Comment by xcodebuild** [comment]
确实对于 iOS Simulator 等使用场景来说存在这个问题，

一键复制到剪贴板的操作在这个页面也有，可以参考 https://github.com/alibaba/lightproxy/blob/master/src/renderer/extensions/phone-proxy/index.tsx#L65

**Comment by KevinChen073** [comment]
soga，那我提个PR。👌

**Comment by xcodebuild** [comment]
fixed with #229
