### ISSUE TITLE
初次打开内存&CPU占用非常高

### ISSUE THREAD

**Issue by isaced** [alibaba/lightproxy#240]
初次打开还未安装证书的时候（弹框复制命令），CPU & 内存占用都非常高（如图）；证书装好后进入基本恢复正常。

环境：MacBook Pro (13-inch, M1, 2020) ｜ macOS 11.2.3

![image](https://user-images.githubusercontent.com/2088605/114497642-2a412e00-9c55-11eb-9974-c6f8d02bb916.png)
![image](https://user-images.githubusercontent.com/2088605/114497655-32996900-9c55-11eb-8514-7677c868dfef.png)

**Comment by xcodebuild** [comment]
第一次启动的时候会解压 node 相关依赖的一个 zip，如果占用资源高可能与此相关 https://github.com/alibaba/lightproxy/blob/master/src/main/main.ts#L180

但是理论上影响的不应该是 GPU 这个进程，而且内存 45G 位面也过于夸张了。是否和 M1 下运行 x86 应用有关？

**Comment by xcodebuild** [comment]
已经做了 Apple M1 的 Native 适配，提高了在 M1 下的性能，目前在 beta 版本：https://github.com/alibaba/lightproxy/releases/tag/v1.1.42-beta-4

**Comment by MatriXiao88** [comment]
@xcodebuild 该问题在这种机器侠仍然存在，现象和一楼的是一样的，就算用了beta版本也还是存在

>   型号名称：	MacBook Pro
  型号标识符：	MacBookPro11,1
  处理器名称：	Dual-Core Intel Core i5
  处理器速度：	2.6 GHz
  处理器数目：	1
  核总数：	2
  L2缓存（每个核）：	256 KB
  L3缓存：	3 MB
  超线程技术：	已启用
  内存：	8 GB
  操作系统：Catalina 10.15.7
