### ISSUE TITLE
LightProxy for Mac 版本的标题栏帮助文档URL指向错误。

### ISSUE THREAD

**Issue by VictorNanka** [alibaba/lightproxy#25]
标题栏的Help->Documentation 点击后指向了Electron的Github页面，造成用户困扰。
![image](https://user-images.githubusercontent.com/30154366/71820640-b4056180-30ca-11ea-9425-8f89844d0113.png)

**Comment by xcodebuild** [comment]
感谢反馈，下个版本修复

**Comment by xcodebuild** [comment]
fixed by https://github.com/alibaba/lightproxy/pull/27
