### ISSUE TITLE
新功能期待，希望提供网速控制功能。我手机代理，有时需要限制网速进行测试呢

### ISSUE THREAD

**Issue by robinwp** [alibaba/lightproxy#251]

**Comment by smileorigin** [comment]
*.xxx.com resSpeed://500

**Comment by robinwp** [comment]
thinks



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: smileorigin ***@***.***&gt;
发送时间: 2021年7月23日 15:03
收件人: alibaba/lightproxy ***@***.***&gt;
抄送: robin ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[alibaba/lightproxy] 新功能期待，希望提供网速控制功能。我手机代理，有时需要限制网速进行测试呢 (#251)





 
*.xxx.com resSpeed://500
