### ISSUE TITLE
使用 ProxyTable 时，域名不正确

### ISSUE THREAD

**Issue by lizy0329** [alibaba/lightproxy#259]
1. 在 Vue 项目中使用了 ProxyTable 的设定
```
proxyTable: {
        '/api': {
            target: 'http://www.bbb.com',
            pathRewrite: { '^/api': '/api' },
            changeOrigin: true
        }
    },
```
在访问 www.aaa.com 时，接口需要请求到 www.bbb.com 域名，这时候 ProxyTable 生效，页面正常渲染。

2. 同时打开 lightproxy，这时候会发现接口显示 404，查看 header 得知
Request URL: www.aaa.com
__lightproxy-real-url__: www.aaa.com （依然不变，期望是 www.bbb.com）

在 lightproxy 添加 
```
# ProxyTable
/\/api\/(.+)/ http://www.bbb.com/api/$1
```
页面正常渲染

功能预期：lightproxy 能够识别出 ProxyTable 经过转换的域名

**Comment by KevinChen073** [comment]
我复述一下我的理解哈，
是为了解决本地开发阶段接口请求跨域的问题，你的本地域名是aaa.com，需要调用bbb.com的接口。然后proxyTable的代理是生效的。但是你使用lightproxy，的时候，配置完规则后，还是请求到了aaa.com对吗？
还有你可以看一下他有没有命中你的规则，你看看lightproxy-rule有没有内容，是none还是你的规则

**Comment by lizy0329** [comment]
> 我复述一下我的理解哈，
> 是为了解决本地开发阶段接口请求跨域的问题，你的本地域名是aaa.com，需要调用bbb.com的接口。然后proxyTable的代理是生效的。但是你使用lightproxy，的时候，配置完规则后，还是请求到了aaa.com对吗？
> 还有你可以看一下他有没有命中你的规则，你看看lightproxy-rule有没有内容，是none还是你的规则

就是说项目里 ProxyTable 一直开启：
1. 在禁止 lightproxy 代理时，转换规则正常，dev.aaa.com 能够跳转到 bbb.com 请求数据
2. 在开启 lightproxy 代理时，转换规则不正常， lightproxy-real-url: dev.aaa.com 依然不变
3. 在开启 lightproxy 代理同时输入上贴 # ProxyTable 规则时，转换规则正常，dev.aaa.com 能够跳转到 bbb.com 请求数据
