### ISSUE TITLE
whistle online password

### ISSUE THREAD

**Issue by YeomanYe** [alibaba/lightproxy#260]
whistle 在线版本的密码是多少，我只看到到用户名没看到密码

![image](https://user-images.githubusercontent.com/18027354/128318391-60351ace-848c-4f03-beb0-3471d9566f90.png)

**Comment by KevinChen073** [comment]
密码在右下角的菜单中。
![image](https://user-images.githubusercontent.com/8446410/129873590-cd538f5a-c797-4eb0-854c-ed76c881c9f2.png)
