### ISSUE TITLE
PC和手机端 https抓不了包的 

### ISSUE THREAD

**Issue by 3thinkthendoit** [alibaba/lightproxy#265]
PC和手机端 https抓不了包的

**Comment by KevinChen073** [comment]
无意冒犯，但是我觉得可能是你的证书没有安装成功

**Comment by MatriXiao88** [comment]
有意冒犯。最起码你应该贴出你的问题场景或者一些截图和日志啊，才好意思说出软件已废啊。

你这都不是为了解决问题而来的，纯粹就是发泄一下心中的不爽，我要是作者，都懒得理你！

**Comment by 3thinkthendoit** [comment]
> 有意冒犯。最起码你应该贴出你的问题场景或者一些截图和日志啊，才好意思说出软件已废啊。
> 
> 你这都不是为了解决问题而来的，纯粹就是发泄一下心中的不爽，我要是作者，都懒得理你！

 你测试过么？全部提示证书错误。手机端fiddler同样抓不了。本来就不打算指望解决。你能抓包你教我一下

**Comment by gaoquanao** [comment]
“fiddler同样抓不了” 更佐证了是你证书有问题而非软件问题；大部分手机App都是做了ssl pinning的除非破解或者内部debug包，本就有些包抓不到

**Comment by 3thinkthendoit** [comment]
> “fiddler同样抓不了” 更佐证了是你证书有问题而非软件问题；大部分手机App都是做了ssl pinning的除非破解或者内部debug包，本就有些包抓不到

用的是软件提供的证书，难不成我自己造个证书，别人fiddler百度就可以解析，这软件就是不行。让开发者自己去解决证书，我还用这软件干毛

**Comment by lizy0329** [comment]
> 无意冒犯，但是我觉得可能是你的证书没有安装成功

冒犯个卵，就是证书安装不成功

**Comment by 3thinkthendoit** [comment]
> > 无意冒犯，但是我觉得可能是你的证书没有安装成功
> 
> 冒犯个卵，就是证书安装不成功

别逞口舌之快，帮我来弄弄？
