### ISSUE TITLE
whistle.patch 似乎不太对

### ISSUE THREAD

**Issue by xqin** [alibaba/lightproxy#31]
https://github.com/alibaba/lightproxy/blob/develop/whistle.patch#L15-L23

https://github.com/alibaba/lightproxy/blob/develop/whistle.patch#L53-L54

patch 后文件中正则表达式里面的 `\` 不见了,  `\r\n` 变成了 `rn` 这个明显有问题的吧?

所以目前已经 release 的这些版本中, 都是有问题的???

![image](https://user-images.githubusercontent.com/1265888/71860757-08422d00-312f-11ea-8329-361acfc196d5.png)

**Comment by xcodebuild** [comment]
由于是比较大的 bug，紧急发了版 `1.1.2` 修复了，感谢反馈
