### ISSUE TITLE
这两天正在规划也写一款这种工具。。。

### ISSUE THREAD

**Issue by sanjinhub** [alibaba/lightproxy#32]
想用 electron 搞个 跨平台的 burp，不知道这款软件以后会往这个方向发展吗？

**Comment by xcodebuild** [comment]
之前没用过 burp，可以描述一下和现在的形态主要差异在哪么

**Comment by sanjinhub** [comment]
@xcodebuild 官网：https://portswigger.net/burp 
使用文章：https://blog.csdn.net/liweibin812/article/details/83650751

**Comment by xcodebuild** [comment]
在 #7 里有提到后面会考虑通过 `Devtools Protocol` 来实现类似 Devtools 的抓包界面 & 功能，定位更倾向于服务前端开发

不过看 `burp` 的定位主要是服务网络安全方面的？我自身可能并不是很理解这方面具体的需求

**Comment by sanjinhub** [comment]
OK，抓包工具太多了，都差不多。burp 是个很好的方向。可以搞一搞。
