### ISSUE TITLE
是否警用系统代理有什么区别？

### ISSUE THREAD

**Issue by qiufeihai** [alibaba/lightproxy#38]
是否警用系统代理有什么区别？都要通过SwitchyOmega设置ip:port

**Comment by Runly** [comment]
@qiufeihai 只有在关闭SwitchyOmega或者SwitchyOmega的情景模式改系统代理时，浏览器才会走系统代理

**Comment by Runly** [comment]
@qiufeihai 只有在关闭SwitchyOmega或者SwitchyOmega的情景模式为“系统代理”时，浏览器才会走系统代理

**Comment by xcodebuild** [comment]
`禁用系统代理` 就必须手动设置端口，否则就不需要

如果在没有禁用的情况下却不经过代理的话，请把 `SwitchyOmega` 等插件的代理设置为 `系统代理`
