### ISSUE TITLE
我已经过滤了AppStore，但是手机上进入appstore仍然显示连不上网

### ISSUE THREAD

**Issue by augustVino** [alibaba/lightproxy#44]
如题，我已经过滤了AppStore，但是手机上进入appstore仍然显示连不上网

**Comment by xcodebuild** [comment]
在设置选项 `常用软件域名白名单` 选项是打开的情况下

![image](https://user-images.githubusercontent.com/5436704/72202588-47a8aa80-349c-11ea-8b20-88b910036b7f.png)

我的 `iPhone XS iOS 13.3`  的 `App Store` 是能正常使用的，是否没有按照这里的引导给手机安装证书：https://alibaba.github.io/lightproxy/wireless-proxy.html#%E5%AE%89%E8%A3%85%E8%AF%81%E4%B9%A6
