### ISSUE TITLE
重启代理之后无法再次监听 12888 端口

### ISSUE THREAD

**Issue by happylindz** [alibaba/lightproxy#6]
现象：重启代理之后端口先是 12888，后出现 5xxxx，重新启动软件来保证监听 12888 端口
预期：希望能一直监听 12888 端口
猜想：怀疑前面进程没有释放完被占用，新进程无法再次监听 12888 端口

**Comment by xcodebuild** [comment]
应该是已经弃用的 `whistle` 进程没有来得及被杀掉
