### ISSUE TITLE
安卓模拟器安装证书无法访问https

### ISSUE THREAD

**Issue by 3thinkthendoit** [alibaba/lightproxy#83]
该证书并非来自可信的授权中心。

**Comment by xcodebuild** [comment]
在无线设备上需要先扫码安装并且信任证书，参考 https://alibaba.github.io/lightproxy/wireless-proxy.html

需要注意的是部分高版本 Android 需要应用开启配置才能使用用户安装的证书，可以先用 Chrome 尝试是否能够工作
