### ISSUE TITLE
添加一个出口转发的端口

### ISSUE THREAD

**Issue by phpmaple** [alibaba/lightproxy#91]
这样可以先走 lighproxy 再走一些代理 like ss 从而可以访问 google 等网站

**Comment by xcodebuild** [comment]
事实上目前可以通过

```shell
/.*/ socks5://127.0.0.1:1080
```

来实现类似的效果，甚至可以写具体的匹配规则。

使用 https://chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif 等 Chrome 插件来控制代理规则可能更加方便

**Comment by phpmaple** [comment]
> 事实上目前可以通过
> 
> ```shell
> /.*/ socks5://127.0.0.1:1080
> ```
> 
> 来实现类似的效果，甚至可以写具体的匹配规则。
> 
> 使用 [chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif](https://chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif) 等 Chrome 插件来控制代理规则可能更加方便

感谢回答，使用 SwitchyOmega 只可以控制规则让他发到 lightproxy 吧，最后出口只可以通过你说的在 Rules 里面配置是吧，我现在开发App用模拟器的话转发到 lightproxy 只能通过覆盖系统代理方式吧，SwitchyOmega 就不行了

**Comment by xcodebuild** [comment]
@phpmaple 是的，如果是要实现出口的方式就只能通过规则实现了，SwitchOmega 只能解决浏览器

**Comment by xcodebuild** [comment]
补充说明下，如果是 HTTP 代理需要写成 

```
/.*/ proxy://127.0.0.1:1080
```
